# ref: https://github.com/docker-library/official-images
name: aarch64 Docker

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

jobs:
  Distros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [alpine, centos, debian, fedora, opensuse, ubuntu]
      fail-fast: false
    env:
      DISTRO: arm64_${{ matrix.distro }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Check docker
      run: |
        docker info
        docker buildx ls
    - name: Build env image
      run: make --directory=ci ${DISTRO}_env
    - name: Build devel project
      run: make --directory=ci ${DISTRO}_devel
    - name: Build project
      run: make --directory=ci ${DISTRO}_build
    - name: Test project
      run: make --directory=ci ${DISTRO}_test

    - name: Build install env image
      run: make --directory=ci ${DISTRO}_install_env
    - name: Build install devel project
      run: make --directory=ci ${DISTRO}_install_devel
    - name: Build install project
      run: make --directory=ci ${DISTRO}_install_build
    - name: Test install project
      run: make --directory=ci ${DISTRO}_install_test
