name: amd64 Linux

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

jobs:
  # Building using the github runner environement directly.
  linux:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         build: [
           ["Unix Makefiles", "Release"],
           ["Ninja", "Release"],
           ["Ninja Multi-Config", "Release"]
         ]
       fail-fast: false
    env:
      GENERATOR: ${{ matrix.build[0] }}
      BUILD_TYPE: ${{ matrix.build[1] }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Ninja
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build
    - name: Uninstall preinstalled swig3.0
      run: |
        swig -version;
        sudo apt remove -y swig swig3.0
    - name: Install SWIG 4.0.2
      run: |
        wget "https://github.com/swig/swig/archive/refs/tags/v4.0.2.tar.gz" -O swig-4.0.2.tar.gz;
        tar xvf swig-4.0.2.tar.gz;
        rm swig-4.0.2.tar.gz;
        cd swig-4.0.2;
        ./autogen.sh;
        ./configure --prefix=/usr;
        make -j8;
        sudo make install;
        cd ..;
        rm -rf swig-4.0.2;
    - name: Check swig
      run: swig -version
    - name: Check cmake
      run: cmake --version
    - name: Configure
      run: cmake -S. -Bbuild -G "$GENERATOR" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DCMAKE_INSTALL_PREFIX=install
    - name: Build
      run: cmake --build build --config "$BUILD_TYPE" --target all -v
    - name: Test
      run: cmake --build build --config "$BUILD_TYPE" --target test -v
    - name: Install
      run: cmake --build build --config "$BUILD_TYPE" --target install -v
