# ref: https://github.com/docker-library/official-images#architectures-other-than-amd64
name: Docker ARMv8 64-bit

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

jobs:
  Distros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [alpine, centos, debian, fedora, manylinux, ubuntu]
      fail-fast: false
    env:
      DISTRO: arm64v8_${{ matrix.distro }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Build env image
      run: make --directory=ci ${DISTRO}_env
    - name: Build devel project
      run: make --directory=ci ${DISTRO}_devel
    - name: Build project
      run: make --directory=ci ${DISTRO}_build
    - name: Test project
      run: make --directory=ci ${DISTRO}_test

    - name: Build env Install
      run: make --directory=ci ${DISTRO}_install_env
    - name: Build devel Install
      run: make --directory=ci ${DISTRO}_install_devel
    - name: Build Install
      run: make --directory=ci ${DISTRO}_install_build
    - name: Test Install
      run: make --directory=ci ${DISTRO}_install_test
